### PR TITLE
#160143957 Create the landing page

### PR DESCRIPTION
**Pull request by bettblake08**
In this pull request is the creation of the UI Template of the homepage of FastFoodFast.

To view the homepage
Open the link below:
https://bettblake08.github.io/Fast-Food-Fast/UI/index.html

Relevant Pivotal Tracker story
#160143957

ScreenShots

### CODE REVIEW

**Comment by ghost** [comment]
This looks good...

**Comment by Darius-Ndubi** [comment]
Great choice of color. Good design work.

**Comment by artorious** [comment]
Looks awesome.

Do you wanna merge into master though? ..... Not develop branch? You can change this on PR without changing code. 

As you continue to build..... Consider [Git-naming-conventions-and-best-practices](https://github.com/andela/bestpractices/wiki/Git-naming-conventions-and-best-practices)

**Comment by SilasKenneth** [comment]
Awesome

**Comment by bettblake08** [comment]
@artorious Thanks a lot. I don't know how I missed that. I will consider it.

**Comment by bettblake08** [comment]
@artorious concerning pushing to master, I believed because we have been developing UI templates instead of the complete project, the master could be left empty until thne.

**Pull request closed without merging**
